version: '3'
services:
  postgres:
    image: postgis/postgis
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    ports:
      - "5432:5432"
    volumes:
      - postgis-data:/var/lib/postgresql

  parse:
    image: parseplatform/parse-server
    environment:
      - PARSE_SERVER_APPLICATION_ID=parse
      - PARSE_SERVER_MASTER_KEY=parse@master123!
      - PARSE_SERVER_DATABASE_URI=postgres://postgres:password@postgres/postgres
      - PARSE_SERVER_MOUNT_PATH=/parse
    ports:
      - '1337:1337'
    entrypoint: ["/bin/sh", "-c", "sleep 5;  node ./bin/parse-server"] #sleep few seconds for postgres to come up
    depends_on:
      - postgres

  parse-dashboard:
    image: parseplatform/parse-dashboard
    ports:
      - '4040:4040'
    environment:
#      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=true
      - PARSE_DASHBOARD_TRUST_PROXY=1
      - PARSE_DASHBOARD_COOKIE_SESSION_SECRET=AB8849B6-D725-4A75-AA73-AB7103F0363F
      - PARSE_DASHBOARD_SERVER_URL=http://localhost:1337/parse
      - PARSE_DASHBOARD_MASTER_KEY=parse@master123!
      - PARSE_DASHBOARD_APP_ID=parse
      - PARSE_DASHBOARD_APP_NAME=MyParseApp
      - PARSE_DASHBOARD_USER_ID=admin
      - PARSE_DASHBOARD_USER_PASSWORD=password
      - MOUNT_PATH=/dashboard/
    command: parse-dashboard --dev
    depends_on:
      - parse
volumes:
  postgis-data:
